apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-kube
  labels:
    app: vue-kube
spec:
  selector:
    matchLabels:
      app: vue-kube
  replicas: 2
  template:
    metadata:
      labels:
        app: vue-kube
    spec:
      containers:
        - name: vue-kube
          image: docker.io/ohansck/vue-kube:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: vue-kube
  name: vue-kube
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: vue-kube
